/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SimpleCitations
});
module.exports = __toCommonJS(main_exports);
var import_obsidian11 = require("obsidian");

// src/settings/settings.ts
var DEFAULT_SETTINGS = {
  jsonPaths: [],
  jsonNames: [],
  folderPath: "",
  includeAuthorTag: false,
  includeJournalTag: false,
  includeBibliography: false,
  optionalFields: "",
  includeAbstract: false,
  templatePath: "",
  autoAddCitations: false,
  autoSyncCitations: false,
  autoUpdateCitations: false,
  mergeStrategies: {},
  showBaseProperties: false,
  jsonUpdatedTimes: {},
  inputPandocPath: "",
  pandocOutputPath: "",
  pandocArgs: "-f markdown+hard_line_breaks",
  includeBbtPdf: true,
  includeBbtCollections: true,
  pdfimagesPath: ""
};

// src/settings/SettingTab.ts
var import_obsidian4 = require("obsidian");

// src/utils/fileStatus.ts
var import_obsidian = require("obsidian");
function setStatusIcon(el, valid) {
  el.empty();
  el.addClass("simple-citations-status");
  el.removeClass("is-valid", "is-invalid");
  el.addClass(valid ? "is-valid" : "is-invalid");
  (0, import_obsidian.setIcon)(el, valid ? "check-circle" : "x-circle");
}
function updateSettingJsonStatus(app, statusSpan, path) {
  if (!path) {
    statusSpan.empty();
    return;
  }
  const normalizedPath = (0, import_obsidian.normalizePath)(path);
  const file = app.vault.getFileByPath(normalizedPath);
  setStatusIcon(statusSpan, !!(file && file.extension === "json"));
}
function updateSettingFolderStatus(app, statusSpan, path) {
  if (!path) {
    statusSpan.empty();
    return;
  }
  const normalizedPath = (0, import_obsidian.normalizePath)(path);
  const folder = app.vault.getAbstractFileByPath(normalizedPath);
  setStatusIcon(statusSpan, !!(folder && folder instanceof import_obsidian.TFolder));
}
function updateSettingTemplateStatus(app, statusSpan, path) {
  if (!path) {
    statusSpan.empty();
    return;
  }
  const normalizedPath = (0, import_obsidian.normalizePath)(path + ".md");
  const file = app.vault.getFileByPath(normalizedPath);
  setStatusIcon(statusSpan, !!file);
}

// src/settings/FileSuggest.ts
var import_obsidian2 = require("obsidian");
var FolderSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.textInputEl = inputEl;
  }
  getSuggestions(inputStr) {
    const lowerInput = inputStr.toLowerCase();
    return this.app.vault.getAllLoadedFiles().filter(
      (f) => f instanceof import_obsidian2.TFolder && f.path.toLowerCase().includes(lowerInput)
    );
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path || "/");
  }
  selectSuggestion(folder) {
    this.setValue(folder.path);
    this.textInputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};
var JsonFileSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl, excludePaths = () => []) {
    super(app, inputEl);
    this.textInputEl = inputEl;
    this.excludePaths = excludePaths;
  }
  getSuggestions(inputStr) {
    const lowerInput = inputStr.toLowerCase();
    const excluded = new Set(this.excludePaths());
    return this.app.vault.getAllLoadedFiles().filter(
      (f) => f instanceof import_obsidian2.TFile && f.extension === "json" && f.path.toLowerCase().includes(lowerInput) && !excluded.has(f.path)
    );
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    this.setValue(file.path);
    this.textInputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};

// src/utils/mergeStrategies.ts
var MERGE_BY_DEFAULT = /* @__PURE__ */ new Set([
  "collections",
  "library"
]);
function getStrategy(overrides, property) {
  const override = overrides[property];
  if (override === "priority" || override === "merge") return override;
  return MERGE_BY_DEFAULT.has(property) ? "merge" : "priority";
}
function getDefaultStrategy(property) {
  return MERGE_BY_DEFAULT.has(property) ? "merge" : "priority";
}
function mergeValues(existing, incoming) {
  if (existing === void 0) return incoming;
  if (incoming === void 0) return existing;
  const arrA = Array.isArray(existing) ? existing : [existing];
  const arrB = Array.isArray(incoming) ? incoming : [incoming];
  const seen = /* @__PURE__ */ new Set();
  const result = [];
  for (const item of [...arrA, ...arrB]) {
    const key = typeof item === "object" && item !== null ? JSON.stringify(item) : String(item);
    if (!seen.has(key)) {
      seen.add(key);
      result.push(item);
    }
  }
  return result;
}

// src/utils/updateFrontMatter.ts
var BASE_PROPERTIES = [
  "title",
  "authors",
  "year",
  "journal",
  "doi",
  "pdf",
  "collections"
];
function extractValuesCsl(item) {
  const vals = {};
  vals.title = item["title"];
  if (item["author"] && Array.isArray(item["author"])) {
    vals.authors = Array.from(new Set(
      item["author"].map(
        (a) => {
          var _a, _b;
          return (a.literal || `${(_a = a.given) != null ? _a : ""} ${(_b = a.family) != null ? _b : ""}`).trim();
        }
      )
    ));
  }
  if (item["issued"] && Array.isArray(item["issued"]["date-parts"])) {
    const dateParts = item["issued"]["date-parts"][0];
    if (dateParts && !isNaN(dateParts[0])) {
      vals.year = Number(dateParts[0]);
    }
  }
  vals.journal = item["container-title"];
  if (item["DOI"]) vals.doi = `https://doi.org/${item["DOI"]}`;
  return vals;
}
function parseBbtYear(date) {
  var _a;
  const trimmed = date.trim();
  const isoMatch = trimmed.match(/^(\d{4})/);
  const slashMatch = !isoMatch ? trimmed.match(/^\d{1,2}\/(\d{4})/) : null;
  const yearStr = (_a = isoMatch == null ? void 0 : isoMatch[1]) != null ? _a : slashMatch == null ? void 0 : slashMatch[1];
  const year = yearStr ? parseInt(yearStr, 10) : NaN;
  return isNaN(year) ? void 0 : year;
}
function extractValuesBbt(item) {
  const vals = {};
  vals.title = item["title"];
  if (Array.isArray(item["creators"])) {
    const authors = item["creators"].filter((c) => c.creatorType === "author").map((c) => {
      var _a, _b, _c;
      return (((_a = c.name) == null ? void 0 : _a.trim()) || `${(_b = c.firstName) != null ? _b : ""} ${(_c = c.lastName) != null ? _c : ""}`).trim();
    }).filter(Boolean);
    if (authors.length > 0) vals.authors = Array.from(new Set(authors));
  }
  if (typeof item["date"] === "string") {
    const year = parseBbtYear(item["date"]);
    if (year !== void 0) vals.year = year;
  }
  vals.journal = item["publicationTitle"];
  if (item["DOI"]) vals.doi = `https://doi.org/${item["DOI"]}`;
  return vals;
}
function extractValues(item) {
  return item["_bbt"] ? extractValuesBbt(item) : extractValuesCsl(item);
}
async function updateFrontMatter(app, settings, targetFile, item, fullSync = false) {
  await app.fileManager.processFrontMatter(targetFile, (fm) => {
    var _a, _b, _c;
    if (fullSync) {
      for (const key of Object.keys(fm)) {
        delete fm[key];
      }
    }
    fm.aliases = [];
    if (!Array.isArray(fm.tags)) {
      fm.tags = fm.tags ? [fm.tags] : [];
    }
    if (item["_bbt"]) {
      const vals = extractValuesBbt(item);
      fm.title = vals.title;
      if (vals.authors) fm.authors = vals.authors;
      if (vals.year !== void 0) fm.year = vals.year;
      fm.journal = vals.journal;
      fm.doi = (_a = vals.doi) != null ? _a : "";
      fm.zotero = (_b = item["select"]) != null ? _b : "";
      if (settings.includeBbtPdf && item["pdf"] !== void 0) {
        fm.pdf = item["pdf"];
      } else {
        delete fm.pdf;
      }
      if (settings.includeBbtCollections && item["collections"] !== void 0) {
        fm.collections = item["collections"];
      } else {
        delete fm.collections;
      }
    } else {
      fm.title = item["title"];
      if (item["author"] && Array.isArray(item["author"])) {
        fm.authors = Array.from(new Set(
          item["author"].map(
            (author) => {
              var _a2, _b2;
              return (author.literal || `${(_a2 = author.given) != null ? _a2 : ""} ${(_b2 = author.family) != null ? _b2 : ""}`).trim();
            }
          )
        ));
      }
      if (item["issued"] && Array.isArray(item["issued"]["date-parts"])) {
        const dateParts = item["issued"]["date-parts"][0];
        if (dateParts && !isNaN(dateParts[0])) {
          fm.year = Number(dateParts[0]);
        }
      }
      fm.journal = item["container-title"];
      fm.doi = item["DOI"] ? `https://doi.org/${item["DOI"]}` : "";
      const groupMatch = (_c = item["zotero_uri"]) == null ? void 0 : _c.match(/\/groups\/(\d+)/);
      fm.zotero = groupMatch ? `zotero://select/groups/${groupMatch[1]}/items/@${item["id"]}` : `zotero://select/items/@${item["id"]}`;
    }
    if (settings.includeBibliography && item["_source_files"] && Array.isArray(item["_source_files"])) {
      fm.bibliography = item["_source_files"];
    } else {
      delete fm.bibliography;
    }
    if (fm.authors && fm.authors.length > 0 && fm.journal && fm.year) {
      fm.aliases.push(`${fm.authors[0]}. ${fm.journal}. ${fm.year}`);
    }
    fm.aliases.push(item["title"]);
    if (fm.authors && fm.authors.length > 0) {
      let authorTag = fm.authors[0].replace(/[&:;,'"\\?!<>|()[\]{}.\s]/g, "_").replace(/_+/g, "_").replace(/^_+|_+$/g, "");
      authorTag = `author/${authorTag}`;
      if (settings.includeAuthorTag) {
        if (!fm.tags.includes(authorTag)) {
          fm.tags.push(authorTag);
        }
      } else {
        const index = fm.tags.indexOf(authorTag);
        if (index > -1) {
          fm.tags.splice(index, 1);
        }
      }
    }
    if (fm.journal) {
      let journalTag = fm.journal.replace(/[&:;,'"\\?!<>|()[\]{}.\s]/g, "_").replace(/_+/g, "_").replace(/^_+|_+$/g, "");
      journalTag = `journal/${journalTag}`;
      if (settings.includeJournalTag) {
        if (!fm.tags.includes(journalTag)) {
          fm.tags.push(journalTag);
        }
      } else {
        const index = fm.tags.indexOf(journalTag);
        if (index > -1) {
          fm.tags.splice(index, 1);
        }
      }
    }
    const optionalFields = settings.optionalFields ? settings.optionalFields.split("\n").map((f) => f.trim()).filter(Boolean) : [];
    for (const field of optionalFields) {
      if (item[field] !== void 0) {
        const value = item[field];
        if (typeof value === "string" || typeof value === "number" || Array.isArray(value) && value.every(
          (v) => typeof v === "string" || typeof v === "number"
        )) {
          fm[field] = value;
        }
      }
    }
    const duplicates = item["_duplicates"] || [];
    for (const dup of duplicates) {
      const dupVals = extractValues(dup);
      for (const [key, val] of Object.entries(dupVals)) {
        if (val === void 0) continue;
        if (getStrategy(settings.mergeStrategies, key) === "merge") {
          fm[key] = mergeValues(fm[key], val);
        }
      }
      for (const field of optionalFields) {
        if (dup[field] === void 0) continue;
        if (getStrategy(settings.mergeStrategies, field) === "merge") {
          const value = dup[field];
          if (typeof value === "string" || typeof value === "number" || Array.isArray(value) && value.every(
            (v) => typeof v === "string" || typeof v === "number"
          )) {
            fm[field] = mergeValues(fm[field], value);
          }
        }
      }
      if (dup["_bbt"]) {
        if (settings.includeBbtPdf && dup["pdf"] !== void 0 && getStrategy(settings.mergeStrategies, "pdf") === "merge") {
          fm.pdf = mergeValues(fm.pdf, dup["pdf"]);
        }
        if (settings.includeBbtCollections && dup["collections"] !== void 0 && getStrategy(settings.mergeStrategies, "collections") === "merge") {
          fm.collections = mergeValues(fm.collections, dup["collections"]);
        }
      }
    }
  });
}

// src/utils/loadBibliographyData.ts
var import_obsidian3 = require("obsidian");
function isBetterBibTeXFormat(data) {
  if (typeof data !== "object" || data === null || Array.isArray(data)) return false;
  const d = data;
  return typeof d.config === "object" && d.config !== null && d.config.label === "BetterBibTeX JSON" && Array.isArray(d.items);
}
function normalizeBbtEntry(item, collectionNames) {
  const normalized = { ...item };
  normalized["citation-key"] = item.citationKey;
  normalized["_bbt"] = true;
  if (item.abstractNote !== void 0) normalized["abstract"] = item.abstractNote;
  if (Array.isArray(item.attachments)) {
    const pdfs = item.attachments.map((a) => {
      var _a;
      return (_a = a.path) != null ? _a : "";
    }).filter((p) => p.toLowerCase().endsWith(".pdf"));
    if (pdfs.length > 0) normalized["pdf"] = pdfs.length === 1 ? pdfs[0] : pdfs;
  }
  if (item.key) {
    const cols = collectionNames.get(item.key);
    if (cols && cols.length > 0) normalized["collections"] = cols;
  }
  return normalized;
}
async function loadBibliographyData(app, jsonPaths, jsonNames) {
  var _a;
  const jsonFiles = [];
  const mergedData = [];
  const seenKeys = /* @__PURE__ */ new Map();
  for (let i = 0; i < jsonPaths.length; i++) {
    const path = jsonPaths[i];
    if (!path) continue;
    const normalizedPath = (0, import_obsidian3.normalizePath)(path);
    const file = app.vault.getFileByPath(normalizedPath);
    if (!file || file.extension !== "json") continue;
    const bibName = ((_a = jsonNames[i]) == null ? void 0 : _a.trim()) || file.basename;
    jsonFiles.push(file);
    const contents = await app.vault.cachedRead(file);
    let data;
    try {
      data = JSON.parse(contents);
    } catch (e) {
      continue;
    }
    let entries;
    if (Array.isArray(data)) {
      entries = data;
    } else if (isBetterBibTeXFormat(data)) {
      const collectionNames = /* @__PURE__ */ new Map();
      if (data.collections) {
        for (const col of Object.values(data.collections)) {
          if (!col.name || !Array.isArray(col.items)) continue;
          for (const itemKey of col.items) {
            if (!collectionNames.has(itemKey)) collectionNames.set(itemKey, []);
            collectionNames.get(itemKey).push(col.name);
          }
        }
      }
      entries = data.items.map((item) => normalizeBbtEntry(item, collectionNames));
    } else {
      continue;
    }
    for (const entry of entries) {
      const key = entry == null ? void 0 : entry["citation-key"];
      if (!key) continue;
      const existing = seenKeys.get(key);
      if (!existing) {
        entry["_source_files"] = [bibName];
        entry["_duplicates"] = [];
        seenKeys.set(key, entry);
        mergedData.push(entry);
      } else {
        existing["_source_files"].push(bibName);
        existing["_duplicates"].push(entry);
      }
    }
  }
  return { jsonFiles, mergedData };
}

// src/settings/SettingTab.ts
var SimpleCitationsSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.mergeContainer = null;
    this.plugin = plugin;
  }
  display() {
    var _a, _b, _c;
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Basic").setHeading();
    const bibSetting = new import_obsidian4.Setting(containerEl).setName("Bibliography file paths").setDesc("Better CSL JSON or BetterBibTeX JSON files. Earlier entries have higher priority when duplicate citation keys exist.").addButton((button) => button.setButtonText("+ Add file").setCta().onClick(async () => {
      this.plugin.settings.jsonPaths.push("");
      this.plugin.settings.jsonNames.push("");
      await this.plugin.saveSettings();
      this.display();
    }));
    bibSetting.settingEl.addClass("simple-citations-bib-setting");
    const bibListEl = bibSetting.settingEl.createDiv({ cls: "simple-citations-bib-list" });
    const paths = this.plugin.settings.jsonPaths;
    if (paths.length === 0) {
      bibListEl.createEl("p", {
        text: "No bibliography files added yet.",
        cls: "simple-citations-bib-empty"
      });
    }
    for (let i = 0; i < paths.length; i++) {
      const idx = i;
      const rowEl = bibListEl.createDiv({ cls: "simple-citations-bib-row" });
      const infoEl = rowEl.createDiv({ cls: "simple-citations-bib-info" });
      const defaultName = ((_b = (_a = paths[idx]) == null ? void 0 : _a.split("/").pop()) == null ? void 0 : _b.replace(/\.json$/, "")) || "";
      const displayName = ((_c = this.plugin.settings.jsonNames[idx]) == null ? void 0 : _c.trim()) || defaultName;
      const showDisplay = () => {
        infoEl.empty();
        const nameRow = infoEl.createDiv({ cls: "simple-citations-bib-name" });
        const statusSpan = nameRow.createSpan();
        updateSettingJsonStatus(this.app, statusSpan, paths[idx]);
        nameRow.createSpan({ text: displayName || "(unnamed)" });
        const pathDiv = infoEl.createDiv({ cls: "simple-citations-bib-path" });
        pathDiv.createSpan({ text: "File path: ", cls: "simple-citations-bib-path-label" });
        pathDiv.createSpan({ text: paths[idx] || "(empty path)" });
      };
      const showEditor = () => {
        infoEl.empty();
        const nameInput = infoEl.createEl("input", { type: "text", cls: "simple-citations-bib-input" });
        nameInput.value = this.plugin.settings.jsonNames[idx] || "";
        nameInput.placeholder = defaultName ? `Display name (default: ${defaultName})` : "Display name (defaults to JSON filename)";
        const pathInput = infoEl.createEl("input", { type: "text", cls: "simple-citations-bib-input simple-citations-bib-input-path" });
        pathInput.value = paths[idx];
        pathInput.placeholder = "Search for a .json file";
        new JsonFileSuggest(
          this.app,
          pathInput,
          () => this.plugin.settings.jsonPaths.filter((_, i2) => i2 !== idx)
        );
        if (!paths[idx]) {
          pathInput.focus();
        } else {
          nameInput.focus();
        }
        const save = async () => {
          var _a2, _b2;
          await new Promise((r) => window.setTimeout(r, 100));
          if (!pathInput.value && !((_a2 = activeDocument.activeElement) == null ? void 0 : _a2.closest(".simple-citations-bib-row"))) {
            this.plugin.settings.jsonPaths.splice(idx, 1);
            this.plugin.settings.jsonNames.splice(idx, 1);
            await this.plugin.saveSettings();
            this.display();
            return;
          }
          const newPath = pathInput.value;
          const duplicate = this.plugin.settings.jsonPaths.some(
            (p, i2) => i2 !== idx && p === newPath
          );
          if (duplicate && newPath) {
            new import_obsidian4.Notice("This bibliography file has already been added.");
            pathInput.value = paths[idx];
            return;
          }
          this.plugin.settings.jsonPaths[idx] = newPath;
          this.plugin.settings.jsonNames[idx] = nameInput.value;
          await this.plugin.saveSettings();
          if (!((_b2 = activeDocument.activeElement) == null ? void 0 : _b2.closest(".simple-citations-bib-row"))) {
            this.display();
          }
        };
        nameInput.addEventListener("blur", () => {
          void save();
        });
        pathInput.addEventListener("blur", () => {
          void save();
        });
        nameInput.addEventListener("keydown", (e) => {
          if (e.key === "Enter") {
            pathInput.focus();
          }
        });
        pathInput.addEventListener("keydown", (e) => {
          if (e.key === "Enter") {
            pathInput.blur();
          }
        });
      };
      if (!paths[i]) {
        showEditor();
      } else {
        showDisplay();
      }
      const btnGroup = rowEl.createDiv({ cls: "simple-citations-bib-buttons" });
      if (i > 0) {
        const upBtn = btnGroup.createEl("button", { cls: "clickable-icon", attr: { "aria-label": "Move up" } });
        (0, import_obsidian4.setIcon)(upBtn, "arrow-up");
        upBtn.addEventListener("click", () => {
          void (async () => {
            const names = this.plugin.settings.jsonNames;
            [paths[idx - 1], paths[idx]] = [paths[idx], paths[idx - 1]];
            [names[idx - 1], names[idx]] = [names[idx], names[idx - 1]];
            await this.plugin.saveSettings();
            this.display();
          })();
        });
      }
      if (i < paths.length - 1) {
        const downBtn = btnGroup.createEl("button", { cls: "clickable-icon", attr: { "aria-label": "Move down" } });
        (0, import_obsidian4.setIcon)(downBtn, "arrow-down");
        downBtn.addEventListener("click", () => {
          void (async () => {
            const names = this.plugin.settings.jsonNames;
            [paths[idx], paths[idx + 1]] = [paths[idx + 1], paths[idx]];
            [names[idx], names[idx + 1]] = [names[idx + 1], names[idx]];
            await this.plugin.saveSettings();
            this.display();
          })();
        });
      }
      const editBtn = btnGroup.createEl("button", { cls: "clickable-icon", attr: { "aria-label": "Edit path" } });
      (0, import_obsidian4.setIcon)(editBtn, "pencil");
      editBtn.addEventListener("click", () => showEditor());
      const delBtn = btnGroup.createEl("button", { cls: "clickable-icon", attr: { "aria-label": "Remove" } });
      (0, import_obsidian4.setIcon)(delBtn, "x");
      delBtn.addEventListener("click", () => {
        void (async () => {
          this.plugin.settings.jsonPaths.splice(idx, 1);
          this.plugin.settings.jsonNames.splice(idx, 1);
          await this.plugin.saveSettings();
          this.display();
        })();
      });
    }
    new import_obsidian4.Setting(containerEl).setName("Set literature note folder path").setDesc("Folder to save literature notes. Default: root folder.").addText((text) => {
      const container = text.inputEl.parentElement;
      let statusSpan = null;
      if (container) {
        statusSpan = container.insertBefore(activeDocument.createElement("span"), text.inputEl);
        updateSettingFolderStatus(this.app, statusSpan, this.plugin.settings.folderPath);
      }
      new FolderSuggest(this.app, text.inputEl);
      return text.setPlaceholder("Enter Relative Path").setValue(this.plugin.settings.folderPath).onChange(async (value) => {
        this.plugin.settings.folderPath = value;
        await this.plugin.saveSettings();
        if (container && statusSpan) {
          updateSettingFolderStatus(this.app, statusSpan, value);
        }
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Auto add citations").setDesc("When enabled, execute add commands automatically when any bibliography file is updated.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoAddCitations).onChange(async (value) => {
      this.plugin.settings.autoAddCitations = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Auto sync citations").setDesc("When enabled, automatically adds and updates all literature notes when any bibliography file is updated.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSyncCitations).onChange(async (value) => {
      this.plugin.settings.autoSyncCitations = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Auto update citations").setDesc("When enabled, automatically updates citation notes when opened.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoUpdateCitations).onChange(async (value) => {
      this.plugin.settings.autoUpdateCitations = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Additional Properties").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Include author tag").setDesc("When enabled, adds a tag with the first author's name.").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeAuthorTag).onChange(async (value) => {
      this.plugin.settings.includeAuthorTag = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Include journal tag").setDesc("When enabled, adds a tag with the journal name.").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeJournalTag).onChange(async (value) => {
      this.plugin.settings.includeJournalTag = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Include bibliography").setDesc('When enabled, adds a "bibliography" property to each literature note as a list, indicating which bibliography file(s) the citation was found in (e.g. ["My Library"]). If the entry appears in multiple files, all sources are listed.').addToggle((toggle) => toggle.setValue(this.plugin.settings.includeBibliography).onChange(async (value) => {
      this.plugin.settings.includeBibliography = value;
      await this.plugin.saveSettings();
    }));
    const bbtPropsContainer = containerEl.createDiv();
    void (async () => {
      const hasBbt = await this.detectBbtFiles();
      if (!hasBbt) return;
      new import_obsidian4.Setting(bbtPropsContainer).setName("Include PDF paths (BetterBibTeX JSON)").setDesc('Automatically adds a "pdf" property with local PDF paths extracted from attachments.').addToggle((toggle) => toggle.setValue(this.plugin.settings.includeBbtPdf).onChange(async (value) => {
        this.plugin.settings.includeBbtPdf = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian4.Setting(bbtPropsContainer).setName("Include collections (BetterBibTeX JSON)").setDesc('Automatically adds a "collections" property with Zotero collection names the item belongs to.').addToggle((toggle) => toggle.setValue(this.plugin.settings.includeBbtCollections).onChange(async (value) => {
        this.plugin.settings.includeBbtCollections = value;
        await this.plugin.saveSettings();
      }));
    })();
    const optionalFieldsSetting = new import_obsidian4.Setting(containerEl).setName("Optional fields").setDesc("Set optional fields from JSON. (Separate by line breaks, 1st level only)").addTextArea((textArea) => textArea.setPlaceholder("key\npdf").setValue(this.plugin.settings.optionalFields).onChange(async (value) => {
      this.plugin.settings.optionalFields = value;
      await this.plugin.saveSettings();
      if (this.mergeContainer) {
        this.renderMergeStrategies(this.mergeContainer);
      }
    }));
    optionalFieldsSetting.settingEl.addClass("simple-citations-mobile-wrap");
    if (paths.filter((p) => p).length > 1) {
      new import_obsidian4.Setting(containerEl).setName("Merge strategies").setDesc("When the same citation key appears in multiple bibliography files, choose how each property is handled.").setHeading();
      this.mergeContainer = containerEl.createDiv({ cls: "simple-citations-merge-list" });
      this.renderMergeStrategies(this.mergeContainer);
    } else {
      this.mergeContainer = null;
    }
    new import_obsidian4.Setting(containerEl).setName("Additional Content").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Include abstract to content").setDesc("When enabled, adds the abstract to the top of each literature note.").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeAbstract).onChange(async (value) => {
      this.plugin.settings.includeAbstract = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Set template file path").setDesc("When setting this, adds the template to the top of each literature note. (Intended for use with dynamic templates such as Dataview.)").addText((text) => {
      const container = text.inputEl.parentElement;
      let statusSpan = null;
      if (container) {
        statusSpan = container.insertBefore(activeDocument.createElement("span"), text.inputEl);
        updateSettingTemplateStatus(this.app, statusSpan, this.plugin.settings.templatePath);
      }
      return text.setPlaceholder("Enter Relative Path").setValue(this.plugin.settings.templatePath).onChange(async (value) => {
        this.plugin.settings.templatePath = value;
        await this.plugin.saveSettings();
        if (container && statusSpan) {
          updateSettingTemplateStatus(this.app, statusSpan, value);
        }
      });
    });
    const pandocHeading = new import_obsidian4.Setting(containerEl).setName("Pandoc").setHeading();
    if (import_obsidian4.Platform.isMobile) {
      const descEl = pandocHeading.descEl;
      descEl.createSpan({ text: "Note: ", cls: "simple-citations-note-label" });
      descEl.appendText("Pandoc is only available on desktop.");
    }
    new import_obsidian4.Setting(containerEl).setName("Pandoc path").setDesc((() => {
      const f = activeDocument.createDocumentFragment();
      f.createEl("a", { text: "Pandoc", href: "https://pandoc.org" });
      f.appendText(" must be installed. Mac/Linux: `which pandoc`, Windows: `where pandoc`.");
      return f;
    })()).addText((text) => text.setPlaceholder("pandoc").setValue(this.plugin.settings.inputPandocPath).onChange(async (value) => {
      this.plugin.settings.inputPandocPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Export folder").setDesc("Absolute path to an export folder.").addText((text) => text.setPlaceholder("Same as target").setValue(this.plugin.settings.pandocOutputPath).onChange(async (value) => {
      this.plugin.settings.pandocOutputPath = value;
      await this.plugin.saveSettings();
    }));
    const pandocArgsSetting = new import_obsidian4.Setting(containerEl).setName("Extra Pandoc arguments").setDesc("Add extra command line arguments for pandoc. Absolute path only. New lines are turned into spaces. Citeproc and bibliography are automatically added.").addTextArea((textArea) => {
      textArea.setPlaceholder("Example: -f markdown+hard_line_breaks").setValue(this.plugin.settings.pandocArgs).onChange(async (value) => {
        this.plugin.settings.pandocArgs = value;
        await this.plugin.saveSettings();
      });
      textArea.inputEl.addClass("simple-citations-pandoc-args-textarea");
    });
    pandocArgsSetting.settingEl.addClass("simple-citations-mobile-wrap");
    const popplerHeading = new import_obsidian4.Setting(containerEl).setName("Poppler").setHeading();
    if (import_obsidian4.Platform.isMobile) {
      popplerHeading.descEl.createSpan({ text: "Note: ", cls: "simple-citations-note-label" });
      popplerHeading.descEl.appendText("Poppler is only available on desktop.");
    }
    new import_obsidian4.Setting(containerEl).setName("pdfimages path").setDesc((() => {
      const f = activeDocument.createDocumentFragment();
      f.createEl("a", { text: "Poppler", href: "https://poppler.freedesktop.org" });
      f.appendText(" must be installed. Mac/Linux: `which pdfimages`, Windows: `where pdfimages`.");
      return f;
    })()).addText((text) => text.setPlaceholder("pdfimages").setValue(this.plugin.settings.pdfimagesPath).onChange(async (value) => {
      this.plugin.settings.pdfimagesPath = value;
      await this.plugin.saveSettings();
    }));
  }
  async detectBbtFiles() {
    for (const path of this.plugin.settings.jsonPaths) {
      if (!path) continue;
      const file = this.app.vault.getFileByPath((0, import_obsidian4.normalizePath)(path));
      if (!file) continue;
      try {
        const contents = await this.app.vault.cachedRead(file);
        const data = JSON.parse(contents);
        if (isBetterBibTeXFormat(data)) return true;
      } catch (e) {
      }
    }
    return false;
  }
  renderMergeStrategies(container) {
    container.empty();
    const optionalFields = this.plugin.settings.optionalFields.split("\n").map((f) => f.trim()).filter(Boolean);
    const baseSet = new Set(BASE_PROPERTIES);
    const customProperties = optionalFields.filter((f) => !baseSet.has(f));
    const renderProperty = (parent, prop) => {
      const defaultStrat = getDefaultStrategy(prop);
      const current = getStrategy(this.plugin.settings.mergeStrategies, prop);
      const isCustom = this.plugin.settings.mergeStrategies[prop] !== void 0;
      new import_obsidian4.Setting(parent).setName(prop).setDesc(isCustom ? `Default: ${defaultStrat}` : "").addDropdown((dropdown) => dropdown.addOption("priority", "Priority").addOption("merge", "Merge").setValue(current).onChange(async (value) => {
        if (value === defaultStrat) {
          delete this.plugin.settings.mergeStrategies[prop];
        } else {
          this.plugin.settings.mergeStrategies[prop] = value;
        }
        await this.plugin.saveSettings();
        this.renderMergeStrategies(container);
      }));
    };
    for (const prop of customProperties) {
      renderProperty(container, prop);
    }
    const baseWrapper = container.createDiv({
      cls: `simple-citations-base-props-wrapper${this.plugin.settings.showBaseProperties ? " is-expanded" : ""}`
    });
    new import_obsidian4.Setting(baseWrapper).setName("Base properties").setDesc("Built-in properties managed by the plugin. Defaults: collections \u2192 Merge, others \u2192 Priority.").addToggle((t) => t.setValue(this.plugin.settings.showBaseProperties).onChange(async (value) => {
      this.plugin.settings.showBaseProperties = value;
      await this.plugin.saveSettings();
      this.renderMergeStrategies(container);
    }));
    if (this.plugin.settings.showBaseProperties) {
      const baseList = baseWrapper.createDiv({ cls: "simple-citations-base-props-list" });
      for (const prop of BASE_PROPERTIES) {
        renderProperty(baseList, prop);
      }
    }
  }
};

// src/commands/autoCitations.ts
var import_obsidian5 = require("obsidian");
function isBibliographyUpdated(settings, file) {
  var _a;
  if (!(file instanceof import_obsidian5.TFile)) return false;
  for (const path of settings.jsonPaths) {
    if (!path) continue;
    if (file.path === (0, import_obsidian5.normalizePath)(path)) {
      const lastKnownTime = (_a = settings.jsonUpdatedTimes[file.path]) != null ? _a : 0;
      return lastKnownTime !== new Date(file.stat.mtime).getTime();
    }
  }
  return false;
}
function autoAddCitations(app, settings, file) {
  if (!settings.autoAddCitations) return;
  if (!isBibliographyUpdated(settings, file)) return;
  app.commands.executeCommandById("simple-citations:add-citations");
}
function autoSyncCitations(app, settings, file) {
  if (!settings.autoSyncCitations) return;
  if (!isBibliographyUpdated(settings, file)) return;
  app.commands.executeCommandById("simple-citations:sync-citations");
}

// src/commands/addCitations.ts
var import_obsidian7 = require("obsidian");

// src/utils/parseFrontmatter.ts
function parseFrontmatter(fileContent) {
  if (!fileContent.startsWith("---\n")) {
    return {
      frontmatter: "",
      content: fileContent
    };
  }
  const secondDelimiterIndex = fileContent.indexOf("\n---\n", 4);
  if (secondDelimiterIndex === -1) {
    return {
      frontmatter: "",
      content: fileContent
    };
  }
  return {
    frontmatter: fileContent.slice(0, secondDelimiterIndex + 5),
    // ---\nまで含める
    content: fileContent.slice(secondDelimiterIndex + 5)
    // 残りの部分
  };
}

// src/utils/trimContent.ts
function trimContent(fileContent) {
  const parsed = parseFrontmatter(fileContent);
  const lines = parsed.content.split("\n");
  while (lines.length && lines[0].trim() === "") {
    lines.shift();
  }
  while (lines.length && lines[lines.length - 1].trim() === "") {
    lines.pop();
  }
  const normalizedContent = lines.join("\n");
  const hasFrontmatter = parsed.frontmatter.length > 0;
  const hasContent = normalizedContent.length > 0;
  if (!hasFrontmatter) {
    return hasContent ? `${normalizedContent}
` : "";
  }
  if (!hasContent) {
    return parsed.frontmatter;
  }
  return `${parsed.frontmatter}
${normalizedContent}
`;
}

// src/utils/addAfterFrontmatter.ts
function addAfterFrontmatter(fileContent, newContent) {
  const { frontmatter, content } = parseFrontmatter(fileContent);
  return frontmatter + newContent + "\n\n" + content;
}

// src/utils/replaceCommentTags.ts
function replaceCommentTags(content, startTag, endTag, replacement) {
  const tagRegex = new RegExp(`${startTag}[\\s\\S]*?${endTag}`);
  const replacementContent = replacement ? `${startTag}
${replacement}
${endTag}` : "";
  return tagRegex.test(content) ? trimContent(content.replace(tagRegex, replacementContent)) : (
    // 置換してからトリム
    replacement ? addAfterFrontmatter(trimContent(content), replacementContent) : trimContent(content)
  );
}

// src/utils/updateContent.ts
async function updateContent(app, targetFile, template, abstract) {
  const normalizedAbstract = typeof abstract === "string" ? abstract : "";
  const trimmedAbstract = normalizedAbstract.split("\n").map((line) => line.trim()).join("\n").replace(/\n{2,}/g, "\n");
  await app.vault.process(targetFile, (fileContent) => {
    fileContent = replaceCommentTags(fileContent, "<!-- START_TEMPLATE -->", "<!-- END_TEMPLATE -->", template);
    fileContent = replaceCommentTags(fileContent, "<!-- START_ABSTRACT -->", "<!-- END_ABSTRACT -->", trimmedAbstract);
    return fileContent;
  });
}

// src/utils/checkRequiredFiles.ts
var import_obsidian6 = require("obsidian");
function checkRequiredFiles(app, settings) {
  const jsonFiles = [];
  for (const path of settings.jsonPaths) {
    if (!path) continue;
    const normalizedPath = (0, import_obsidian6.normalizePath)(path);
    const file = app.vault.getFileByPath(normalizedPath);
    if (file && file.extension === "json") {
      jsonFiles.push(file);
    }
  }
  if (jsonFiles.length === 0) {
    new import_obsidian6.Notice(`No valid JSON files found. Please check bibliography file paths in settings.`);
    return {
      jsonFiles: [],
      folder: null,
      templateFile: null,
      error: `No valid JSON files found`
    };
  }
  const normalizedFolderPath = (0, import_obsidian6.normalizePath)(settings.folderPath);
  const folder = app.vault.getAbstractFileByPath(normalizedFolderPath);
  const isFolder = folder && folder instanceof import_obsidian6.TFolder;
  if (!isFolder) {
    new import_obsidian6.Notice(`Folder not found: ${normalizedFolderPath}`);
    return {
      jsonFiles: [],
      folder: null,
      templateFile: null,
      error: `Folder not found: ${normalizedFolderPath}`
    };
  }
  const normalizedTemplatePath = (0, import_obsidian6.normalizePath)(settings.templatePath + ".md");
  const templateFile = app.vault.getFileByPath(normalizedTemplatePath);
  return {
    jsonFiles,
    folder,
    templateFile
  };
}

// src/utils/validateCitekey.ts
function validateCitekey(citekey) {
  if (!citekey) {
    console.log(`Skip item with empty citekey`);
    return false;
  }
  const invalidChars = /[#^[\]|\\/:]/;
  if (invalidChars.test(citekey)) {
    console.log(`Skip item with invalid citekey: ${citekey}
citekey must not contain #, ^, [, ], |, \\, /, :`);
    return false;
  }
  return true;
}

// src/commands/addCitations.ts
var AddCitations = class {
  constructor(app, settings, saveSettings) {
    this.app = app;
    this.settings = settings;
    this.saveSettings = saveSettings;
  }
  registerCommands(plugin) {
    plugin.addCommand({
      id: "add-citations",
      name: "Add literature notes",
      callback: () => this.runAddCitations()
    });
  }
  async runAddCitations() {
    var _a, _b, _c;
    const startTime = performance.now();
    const { jsonFiles, folder, templateFile } = checkRequiredFiles(this.app, this.settings);
    if (jsonFiles.length === 0 || !folder) return;
    const { mergedData } = await loadBibliographyData(this.app, this.settings.jsonPaths, this.settings.jsonNames);
    const files = new Map(folder.children.map((file) => [file.name, file]));
    let templateContent = templateFile ? await this.app.vault.cachedRead(templateFile) : "";
    let fileCount = 0;
    let notice = null;
    let intervalId = null;
    for (let i = 0; i < mergedData.length; i++) {
      const citekey = (_b = (_a = mergedData[i]) == null ? void 0 : _a["citation-key"]) != null ? _b : "";
      if (!validateCitekey(citekey)) continue;
      const targetFileName = "@" + citekey + ".md";
      const targetFile = files.get(targetFileName);
      if (!targetFile) {
        const newFile = await this.app.vault.create(`${folder.path}/${targetFileName}`, "");
        await updateFrontMatter(this.app, this.settings, newFile, mergedData[i]);
        await updateContent(
          this.app,
          newFile,
          templateContent,
          this.settings.includeAbstract ? (_c = mergedData[i]["abstract"]) != null ? _c : "" : ""
        );
        fileCount++;
        if (fileCount === 1) {
          notice = new import_obsidian7.Notice(`${fileCount} file(s) added.`, 0);
          intervalId = window.setInterval(() => {
            notice == null ? void 0 : notice.setMessage(`${fileCount} file(s) added.`);
          }, 200);
        }
      }
    }
    if (intervalId) {
      window.clearInterval(intervalId);
    }
    if (notice) {
      const endTime = performance.now();
      const elapsedTime = ((endTime - startTime) / 1e3).toFixed(1);
      notice.setMessage(`${fileCount} file(s) added.
Time taken: ${elapsedTime} seconds`);
      window.setTimeout(() => {
        notice == null ? void 0 : notice.hide();
      }, 3e3);
    }
    for (const jsonFile of jsonFiles) {
      this.settings.jsonUpdatedTimes[jsonFile.path] = new Date(jsonFile.stat.mtime).getTime();
    }
    await this.saveSettings();
    console.log("Add literature notes completed.");
  }
};

// src/commands/updateCitations.ts
var import_obsidian8 = require("obsidian");
var UpdateCitations = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  registerCommands(plugin) {
    plugin.addCommand({
      id: "update-citations",
      name: "Update literature notes",
      callback: () => this.updateCitations()
    });
    plugin.addCommand({
      id: "update-citations-active",
      name: "Update literature note (active file)",
      callback: () => this.updateCitationsActive()
    });
  }
  async updateCitations(fullSync = false) {
    var _a, _b, _c;
    const startTime = performance.now();
    const { jsonFiles, folder, templateFile } = checkRequiredFiles(this.app, this.settings);
    if (jsonFiles.length === 0 || !folder) return;
    const { mergedData } = await loadBibliographyData(this.app, this.settings.jsonPaths, this.settings.jsonNames);
    const files = new Map(folder.children.map((file) => [file.name, file]));
    let templateContent = templateFile ? await this.app.vault.cachedRead(templateFile) : "";
    let fileCount = 0;
    let notice = new import_obsidian8.Notice(`0 file(s) updated.`, 0);
    const intervalId = window.setInterval(() => {
      notice.setMessage(`${fileCount} file(s) updated.`);
    }, 200);
    for (let i = 0; i < mergedData.length; i++) {
      const citekey = (_b = (_a = mergedData[i]) == null ? void 0 : _a["citation-key"]) != null ? _b : "";
      if (!validateCitekey(citekey)) continue;
      const targetFileName = "@" + citekey + ".md";
      const targetFile = files.get(targetFileName);
      if (targetFile && targetFile instanceof import_obsidian8.TFile) {
        const before = await this.app.vault.read(targetFile);
        await updateFrontMatter(this.app, this.settings, targetFile, mergedData[i], fullSync);
        await updateContent(
          this.app,
          targetFile,
          templateContent,
          this.settings.includeAbstract ? (_c = mergedData[i]["abstract"]) != null ? _c : "" : ""
        );
        const after = await this.app.vault.read(targetFile);
        if (before !== after) fileCount++;
      }
    }
    window.clearInterval(intervalId);
    const endTime = performance.now();
    const elapsedTime = ((endTime - startTime) / 1e3).toFixed(1);
    notice.setMessage(`${fileCount} file(s) updated.
Time taken: ${elapsedTime} seconds`);
    window.setTimeout(() => {
      notice.hide();
    }, 3e3);
  }
  async updateCitationsActive() {
    var _a, _b;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian8.Notice("No active file.");
      return;
    }
    if (!activeFile.name.startsWith("@") || !activeFile.name.endsWith(".md")) {
      new import_obsidian8.Notice("Active file is not a citation note.");
      return;
    }
    const { jsonFiles, folder, templateFile } = checkRequiredFiles(this.app, this.settings);
    if (jsonFiles.length === 0 || !folder) return;
    if (activeFile.parent !== folder) {
      new import_obsidian8.Notice("Active file is not in the configured literature notes folder.");
      return;
    }
    const citekey = activeFile.name.slice(1, -3);
    const { mergedData } = await loadBibliographyData(this.app, this.settings.jsonPaths, this.settings.jsonNames);
    let templateContent = templateFile ? await this.app.vault.cachedRead(templateFile) : "";
    const matchingEntry = mergedData.find((item) => (item == null ? void 0 : item["citation-key"]) === citekey);
    if (!matchingEntry) {
      new import_obsidian8.Notice(`No citation data found for "${citekey}" in any bibliography file.`);
      return;
    }
    if (!validateCitekey((_a = matchingEntry["citation-key"]) != null ? _a : "")) {
      new import_obsidian8.Notice(`Invalid citation key: "${matchingEntry["citation-key"]}"`);
      return;
    }
    await updateFrontMatter(this.app, this.settings, activeFile, matchingEntry);
    await updateContent(
      this.app,
      activeFile,
      templateContent,
      this.settings.includeAbstract ? (_b = matchingEntry["abstract"]) != null ? _b : "" : ""
    );
    new import_obsidian8.Notice("Active file updated.");
  }
  async autoUpdateCitations(file) {
    var _a, _b;
    if (!file) return;
    if (!this.settings.autoUpdateCitations) return;
    if (!file.name.startsWith("@") || !file.name.endsWith(".md")) {
      return;
    }
    const { jsonFiles, folder, templateFile } = checkRequiredFiles(this.app, this.settings);
    if (jsonFiles.length === 0 || !folder) return;
    if (file.parent !== folder) {
      return;
    }
    const citekey = file.name.slice(1, -3);
    const { mergedData } = await loadBibliographyData(this.app, this.settings.jsonPaths, this.settings.jsonNames);
    let templateContent = templateFile ? await this.app.vault.cachedRead(templateFile) : "";
    const matchingEntry = mergedData.find((item) => (item == null ? void 0 : item["citation-key"]) === citekey);
    if (!matchingEntry) {
      return;
    }
    if (!validateCitekey((_a = matchingEntry["citation-key"]) != null ? _a : "")) {
      return;
    }
    await updateFrontMatter(this.app, this.settings, file, matchingEntry);
    await updateContent(
      this.app,
      file,
      templateContent,
      this.settings.includeAbstract ? (_b = matchingEntry["abstract"]) != null ? _b : "" : ""
    );
    console.log(`Auto update citations completed for: ${file.name}`);
  }
};

// src/commands/syncCitations.ts
var import_obsidian9 = require("obsidian");
var SyncCitations = class {
  constructor(app, addCitations, updateCitations) {
    this.app = app;
    this.addCitations = addCitations;
    this.updateCitations = updateCitations;
  }
  registerCommands(plugin) {
    plugin.addCommand({
      id: "sync-citations",
      name: "Sync literature notes",
      callback: async () => {
        await this.addCitations.runAddCitations();
        await this.updateCitations.updateCitations();
      }
    });
    plugin.addCommand({
      id: "full-sync-citations",
      name: "Full sync literature notes (reset all properties)",
      callback: async () => {
        const modal = new import_obsidian9.Modal(this.app);
        modal.setTitle("Full sync literature notes");
        modal.contentEl.createEl("p", {
          text: "This will clear ALL existing properties in each literature note and rebuild them entirely from the bibliography JSON and current settings. Any manually added properties will be lost."
        });
        modal.contentEl.createEl("p", {
          text: 'This is useful when settings or bibliography structure have changed and you want a clean sync. Use normal "Sync literature notes" if you only want to add and update.',
          cls: "mod-warning"
        });
        new import_obsidian9.Setting(modal.contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => modal.close())).addButton((btn) => btn.setButtonText("Full sync").setWarning().onClick(async () => {
          modal.close();
          await this.addCitations.runAddCitations();
          await this.updateCitations.updateCitations(true);
        }));
        modal.open();
      }
    });
  }
};

// src/utils/convertToPandocFormat.ts
function convertToPandocFormat(content) {
  let result = content.replace(/\[\[(.*?)\|.*?\]\]/g, "[[$1]]");
  result = result.replace(/\[\[@(.*?)\]\]/g, "[@$1]");
  result = result.replace(/\](\s*?)\[@/g, ";@");
  result = result.replace(/(\.)\s*?(\[@.*?\])/g, " $2$1 ");
  return result;
}

// src/commands/pdfCommands.ts
var import_obsidian10 = require("obsidian");
function resolvePdfPaths(app, view) {
  var _a, _b;
  const file = view.file;
  if (!file) return null;
  const pdf = (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.pdf;
  if (!pdf) {
    new import_obsidian10.Notice("No PDF path specified in frontmatter.");
    return null;
  }
  return Array.isArray(pdf) ? pdf : [pdf];
}
function registerPdfCommands(plugin, app, getSettings) {
  if (!import_obsidian10.Platform.isDesktop) return;
  plugin.addCommand({
    id: "export-pdf",
    name: "Export PDF",
    editorCallback: async (_editor, view) => {
      const settings = getSettings();
      if (!settings.pandocOutputPath) {
        new import_obsidian10.Notice("Export folder is not set.");
        return;
      }
      const pdfPaths = resolvePdfPaths(app, view);
      if (!pdfPaths) return;
      try {
        const { copyFile } = require("fs/promises");
        const { basename, join } = require("path");
        for (const src of pdfPaths) {
          await copyFile(src, join(settings.pandocOutputPath, basename(src)));
        }
        new import_obsidian10.Notice("PDF export completed.");
      } catch (error) {
        new import_obsidian10.Notice("PDF export failed: " + error.message);
      }
    }
  });
  plugin.addCommand({
    id: "export-pdf-images",
    name: "Export PDF images",
    editorCallback: async (_editor, view) => {
      const settings = getSettings();
      if (!settings.pandocOutputPath) {
        new import_obsidian10.Notice("Export folder is not set.");
        return;
      }
      const pdfPaths = resolvePdfPaths(app, view);
      if (!pdfPaths) return;
      const pdfimagesPath = settings.pdfimagesPath || "pdfimages";
      try {
        const { spawn } = require("child_process");
        const { join } = require("path");
        for (let i = 0; i < pdfPaths.length; i++) {
          const prefix = join(settings.pandocOutputPath, `pdf${i + 1}`);
          await new Promise((resolve, reject) => {
            const proc = spawn(pdfimagesPath, ["-png", pdfPaths[i], prefix], { env: process.env });
            proc.on("close", (code) => {
              if (code === 0) resolve();
              else reject(new Error(`pdfimages exited with code ${code}`));
            });
            proc.on("error", reject);
          });
        }
        new import_obsidian10.Notice("PDF image export completed.");
      } catch (error) {
        new import_obsidian10.Notice("PDF image export failed: " + error.message);
      }
    }
  });
}

// src/main.ts
var SimpleCitations = class extends import_obsidian11.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCitations = new AddCitations(this.app, this.settings, () => this.saveSettings());
    this.updateCitations = new UpdateCitations(this.app, this.settings);
    this.syncCitations = new SyncCitations(this.app, this.addCitations, this.updateCitations);
    this.addCitations.registerCommands(this);
    this.updateCitations.registerCommands(this);
    this.syncCitations.registerCommands(this);
    registerPdfCommands(this, this.app, () => this.settings);
    if (import_obsidian11.Platform.isDesktop) this.addCommand({
      id: "execute-pandoc",
      name: "Pandoc Citeproc Execution (docx)",
      callback: async () => {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile) {
          new import_obsidian11.Notice("No active file.");
          return;
        }
        const content = await this.app.vault.read(activeFile);
        const newContent = convertToPandocFormat(content);
        await this.app.vault.modify(activeFile, newContent);
        const BasePath = this.app.vault.adapter.getBasePath();
        const PandocPath = (0, import_obsidian11.normalizePath)(this.settings.inputPandocPath) || "pandoc";
        const CurrentFilePath = (0, import_obsidian11.normalizePath)(activeFile.path);
        const CurrentFileFolder = CurrentFilePath.split("/").slice(0, -1).join("/");
        const CurrentFileName = CurrentFilePath.split("/").pop();
        const PandocInputFile = BasePath + "/" + CurrentFilePath;
        const PandocOutputPath = this.settings.pandocOutputPath ? (0, import_obsidian11.normalizePath)(this.settings.pandocOutputPath) : BasePath + "/" + CurrentFileFolder;
        const PandocOutputFile = PandocOutputPath + "/" + (CurrentFileName == null ? void 0 : CurrentFileName.replace(/\.md$/, ".docx"));
        const PandocExtraArgs = this.settings.pandocArgs ? this.settings.pandocArgs.split(/[\s\n]+/) : [];
        const bibArgs = [];
        for (const path of this.settings.jsonPaths) {
          if (!path) continue;
          const normalizedPath = (0, import_obsidian11.normalizePath)(path);
          const bibFile = this.app.vault.getFileByPath(normalizedPath);
          if (!bibFile) continue;
          const bibContents = await this.app.vault.cachedRead(bibFile);
          let bibParsed;
          try {
            bibParsed = JSON.parse(bibContents);
          } catch (e) {
            continue;
          }
          if (isBetterBibTeXFormat(bibParsed)) continue;
          bibArgs.push("--bibliography", BasePath + "/" + normalizedPath);
        }
        if (bibArgs.length === 0) {
          new import_obsidian11.Notice("Pandoc execution cancelled: no CSL JSON bibliography files found. BetterBibTeX JSON is not supported by citeproc.");
          await this.app.vault.modify(activeFile, content);
          return;
        }
        const PandocArgs = [
          "--citeproc",
          ...bibArgs,
          ...PandocExtraArgs
        ];
        try {
          const { spawn } = require("child_process");
          const pandocProcess = spawn(
            PandocPath,
            [PandocInputFile, "-o", PandocOutputFile, ...PandocArgs],
            { env: process.env }
          );
          pandocProcess.on("error", (err) => {
            new import_obsidian11.Notice(`Pandoc execution failed: ${err.message}`);
          });
          pandocProcess.on("close", (code) => {
            void (async () => {
              if (code === 0) {
                new import_obsidian11.Notice("Pandoc execution completed successfully.");
              } else {
                new import_obsidian11.Notice(`Pandoc execution failed with code: ${code}`);
              }
              await this.app.vault.modify(activeFile, content);
            })();
          });
        } catch (error) {
          new import_obsidian11.Notice(`An error occurred: ${error.message}`);
          await this.app.vault.modify(activeFile, content);
        }
      }
    });
    this.addCommand({
      id: "convert-to-pandoc-format",
      name: "Convert to Pandoc format",
      callback: async () => {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile) {
          new import_obsidian11.Notice("No active file.");
          return;
        }
        const content = await this.app.vault.read(activeFile);
        const newContent = convertToPandocFormat(content);
        await this.app.vault.modify(activeFile, newContent);
        new import_obsidian11.Notice("Converted to Pandoc format.");
      }
    });
    this.addCommand({
      id: "copy-missing-note-links",
      name: "Copy missing note links not included in json file",
      callback: async () => {
        const { jsonFiles, folder } = checkRequiredFiles(this.app, this.settings);
        if (jsonFiles.length === 0 || !folder) return;
        const { mergedData } = await loadBibliographyData(this.app, this.settings.jsonPaths, this.settings.jsonNames);
        const files = folder.children.filter((file) => file instanceof import_obsidian11.TFile);
        const fileNames = files.map((file) => file.name.replace(/\.md$/, ""));
        const citationKeys = new Set(mergedData.map((entry) => entry["citation-key"]));
        const missingFiles = fileNames.filter((fileName) => !citationKeys.has(fileName.slice(1)));
        if (missingFiles.length === 0) {
          new import_obsidian11.Notice("No missing notes found.");
          return;
        }
        const missingLinks = missingFiles.map((fileName) => `[[${fileName}]]`).join("\n");
        await navigator.clipboard.writeText(missingLinks);
        new import_obsidian11.Notice("Copied missing note links to clipboard!");
      }
    });
    this.addSettingTab(new SimpleCitationsSettingTab(this.app, this));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (!(file instanceof import_obsidian11.TFile)) return;
      autoAddCitations(this.app, this.settings, file);
      autoSyncCitations(this.app, this.settings, file);
    }));
    this.registerEvent(this.app.workspace.on("file-open", (file) => {
      void this.updateCitations.autoUpdateCitations(file);
    }));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.jsonPaths.length > 0 && this.settings.jsonPaths[0]) {
        const firstFile = this.app.vault.getFileByPath((0, import_obsidian11.normalizePath)(this.settings.jsonPaths[0]));
        if (firstFile) {
          autoAddCitations(this.app, this.settings, firstFile);
        }
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    let needsSave = false;
    if (data && "jsonPath" in data && typeof data.jsonPath === "string" && data.jsonPath) {
      if (!this.settings.jsonPaths || this.settings.jsonPaths.length === 0) {
        this.settings.jsonPaths = [data.jsonPath];
      }
      delete this.settings.jsonPath;
      needsSave = true;
    }
    if (data && "jsonUpdatedTime" in data && typeof data.jsonUpdatedTime === "number") {
      if (!this.settings.jsonUpdatedTimes || Object.keys(this.settings.jsonUpdatedTimes).length === 0) {
        for (const path of this.settings.jsonPaths) {
          if (path) {
            this.settings.jsonUpdatedTimes[(0, import_obsidian11.normalizePath)(path)] = data.jsonUpdatedTime;
          }
        }
      }
      delete this.settings.jsonUpdatedTime;
      needsSave = true;
    }
    if (!Array.isArray(this.settings.jsonPaths)) {
      this.settings.jsonPaths = [];
    }
    if (!Array.isArray(this.settings.jsonNames)) {
      this.settings.jsonNames = [];
    }
    while (this.settings.jsonNames.length < this.settings.jsonPaths.length) {
      this.settings.jsonNames.push("");
    }
    if (!this.settings.jsonUpdatedTimes || typeof this.settings.jsonUpdatedTimes !== "object") {
      this.settings.jsonUpdatedTimes = {};
    }
    if (needsSave) {
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */